### PR TITLE
add conf tagline

### PR DESCRIPTION
**Pull request by theutahkate**
So...there's nothing on the page that actually says we're a conference. I added a simple tagline at the top to do so. Wording thoughts? Talk amongst yourselves.

### CODE REVIEW

**Comment by kerrizor** [comment]
Not bad! Anyone else?

**Comment by khjrtbrg** [comment]
@theutahkate @kerrizor What do you think about putting the tagline inside the purple part? 
screen shot 2015-06-18 at 9 58 27 pm

**Comment by kerrizor** [comment]
love it. ship it.

**Comment by theutahkate** [comment]
Totes. That looks great!

**Comment by kerrizor** [comment]
Let's get this out! :)

**Pull request merged**
