### PR TITLE
Move the jumbotron default styles to be up with the @mobile rules to fix cascade issue affecting mobile display

### PR DESCRIPTION
**Pull request by jnf**

### CODE REVIEW

**Comment by strand** [comment]
I trust you on this change, but am curious, what was the cascade issue?

**Comment by jnf** [comment]
The `@media` query doesn't add specificity to the rules it contains. It just decides whether or not the selectors/styles are added to the cascade.

So, even if the query triggers and enables the image width, a later selector was overruling it. The two rules had equal specificity, so the one later in the file took precedence.

**Comment by strand** [comment]
Generally, should we be putting `@media` queries at the end of our CSS?

**Comment by jnf** [comment]
Generally, when not using SASS, I extract media queries into their own stylesheet and load it last.

**Pull request merged**
